### ISSUE TITLE
Lyircs not showing.

### ISSUE THREAD

**Issue by notiicj** [SpikeNew7774/spicy-lyrics#10]
earlier today it was working fine but now it stopped it's not showing not even loading too.

i also wanted to say thank you for who ever is working on this i see how hard you're working and how fast you respond and fr thank you for the hard work you're putting into this you're a legend + i want to star it but i can't figure out how.

**Comment by zydiaa** [comment]
Could you please provide your spotify version and the console.

**Comment by SpikeNew7774** [comment]
@notiicj Also if you could provide some screenshots or examples.

**Comment by notiicj** [comment]
> @notiicj Also if you could provide some screenshots or examples.

sure here : 

![image](https://github.com/user-attachments/assets/e4413c22-6473-4561-aff0-7705ee22bcb3)

**Comment by Mysticc28** [comment]
> > Could you please provide your spotify version and the console.
> 
> I'm sorry but idk how if u could tell me it'll be nice

Open Spotify
3 dots in top left corner
About Spotify - screenshot it

You need dev tools for this one
Right click anywhere
Inspect
Dev tools window opens up, there will be section called console, click that and screenshot

**Comment by notiicj** [comment]
> > > Could you please provide your spotify version and the console.
> > 
> > 
> > I'm sorry but idk how if u could tell me it'll be nice
> 
> Open Spotify 3 dots in top left corner About Spotify - screenshot it
> 
> You need dev tools for this one Right click anywhere Inspect Dev tools window opens up, there will be section called console, click that and screenshot
> 
> Hope that helps

ty and here

![image](https://github.com/user-attachments/assets/f30a88e4-5c50-472c-91d8-ace77b426fa8)

**Comment by notiicj** [comment]
> @notiicj To try to fix the problem. I also need the console screenshot.

for some reason right clicking doesn't do anything for me @SpikeNew7774

**Comment by notiicj** [comment]
> @notiicj To try to fix the problem. I also need the console screenshot.

this is what come when it turn it off and on again
![image](https://github.com/user-attachments/assets/29027675-25d0-43e6-97f9-d73fa7e6b35a)

**Comment by SpikeNew7774** [comment]
@notiicj The Error "Error: slot-not-defined" is not coming from my extension. But thanks, beacuse I just noticed there's some console.logs I need to remove.

**Comment by notiicj** [comment]
> @notiicj The Error "Error: slot-not-defined" is not coming from my extension. But thanks, beacuse I just noticed there's some console.logs I need to remove.

haha np ima try removing my other extensions and try again ill update u aftrer

**Comment by notiicj** [comment]
@SpikeNew7774 i have tried everything still not working... evem deleted spicetify and reinstalled it and still nothing

**Comment by SpikeNew7774** [comment]
@notiicj To look into this deeply, if you want you can provide a short screenrecording of what happens when, when you do that or that.

**Comment by notiicj** [comment]
> @notiicj To look into this deeply, if you want you can provide a short screenrecording of what happens when, when you do that or that.

@SpikeNew7774  sure

**Comment by notiicj** [comment]
https://github.com/user-attachments/assets/17c66c6d-667b-4c73-84d7-17d0054abbe7
@SpikeNew7774  here is my console i reloaded spotify and this is whats happening
