### ISSUE TITLE
[Bug] Scroll bar shows itself when lyrics auto-scroll

### ISSUE THREAD

**Issue by Ender-Wang** [SpikeNew7774/spicy-lyrics#11]
The scroll bar shows up repeatedly, which is kind of annoying and disturbing. It would be much nicer if it stayed hidden when the lyrics auto-scroll as the song plays. I would suggest just disable the scroll.
	![CleanShot_2024-11-18_00-35-33](https://github.com/user-attachments/assets/94497af1-21e0-47ee-aad2-63460d45214a)

**Comment by SpikeNew7774** [comment]
@Ender-Wang Fixed Now!

**Comment by SpikeNew7774** [comment]
@Ender-Wang Fixed Now!
