### ISSUE TITLE
Animation Timing Configuration

### ISSUE THREAD

**Issue by fitsfer** [SpikeNew7774/spicy-lyrics#27]
I wish I could edit the duration of the animation or outright set it to 0 seconds. By the time the next lyric is being spoken, the text hasn't shifted fast enough, making it sort of disorienting.

**Comment by SpikeNew7774** [comment]
@fitsfer Thanks for reporting that problem. I think I know now whats the problem. There will probably be an update today.

**Comment by SpikeNew7774** [comment]
@fitsfer Found out that this is probably a Spicetify Problem. Unfortunetaly I'm not able to fully fix that, but I tried to do some optimizations.
