### ISSUE TITLE
Lyrics not showing again...

### ISSUE THREAD

**Issue by notiicj** [SpikeNew7774/spicy-lyrics#31]
a while back i had an issue that the lyrics are not showing and then i deleted spicetify and reseted everything and deleted spotify and reinstalled everything and it worked again but it was a temporary fix. is there any real fix?

**Comment by SpikeNew7774** [comment]
@notiicj Can you provide short screen recording or screenshots (preferrably the first one)?

**Comment by notiicj** [comment]
@SpikeNew7774 
![Screenshot 2024-11-18 141807](https://github.com/user-attachments/assets/657ceb2d-0624-4a34-b2c2-3a526309f610)

**Comment by SpikeNew7774** [comment]
@notiicj What other extensions you use. If you want, you can also provide the list of extensions and the console screenshots.

Console Screenshots tutorial
1. Run (In your terminal of choice) ```spicetify enable-devtools```
2. After the Spotify app restarts, right click on a space, where the Spotify's right-click menu doesn't display.
3. Click "Inspect"
4. On the top of the new window, click "Console"
5. Then make a screenshot of that!

**Comment by notiicj** [comment]
@SpikeNew7774 
![image](https://github.com/user-attachments/assets/aff089fe-aa19-4982-82b6-763309bf5f72)

**Comment by SpikeNew7774** [comment]
@notiicj I tried literally the same song, and it worked for me.
![image](https://github.com/user-attachments/assets/6383be0c-951f-4f36-a76d-9863791fa4ea)

**Comment by notiicj** [comment]
@SpikeNew7774 yeah for u but for me it doesn't and on every song not just that one

**Comment by notiicj** [comment]
@SpikeNew7774  i was looking in settings and saw "Custom lyrics API" and the link for it was "https://api.spicy-lyrics.spikerko.org/lyrics/{SPOTIFY_ID}" and when i opened the link it got "{"error":"Missing authorization header"}" is that normal?

**Comment by notiicj** [comment]
@SpikeNew7774 well... i tried changing the API to a random one off of github and it worked but it said no lyrics found so i tried the same link that was in again and it started working again sooooo

**Comment by SpikeNew7774** [comment]
@SpikeNew7774 I'm Happy to see that it works! The app only recognizes the "beautiful-lyrics" API format. So if you put a random API on it, it wont work.

**Comment by notiicj** [comment]
well idrm as long as it works now
