### ISSUE TITLE
Lyric auto scroll isnt working

### ISSUE THREAD

**Issue by JokerJosh0** [SpikeNew7774/spicy-lyrics#37]
It doesnt auto scroll to the currently playing lyric, you have to manually scroll to it

**Comment by SpikeNew7774** [comment]
@JokerJosh0 I'm actually working on that problem right now with an updated (that I hope) will be released later today. For now, the only thing that works is restarting the Spotify App.

**Comment by JokerJosh0** [comment]
nevermind it just started working out of nowhere

**Comment by JokerJosh0** [comment]
your comment loaded in as soon as i sent mine, thank you
