### ISSUE TITLE
Required Features 🙏

### ISSUE THREAD

**Issue by zydiaa** [SpikeNew7774/spicy-lyrics#4]
Hello @SpikeNew7774 , thank you really much for creating this extension.
This is just a wish page for things we would like you to add, anyone is free to add features:

- Fullscreen Mode
- Fix "Current Playing Page" Video
- Add Lyrics to the "Current Playing Page"

these are only wishes so dont hurry or even do them if you dont want to. 🐱

**Comment by SpikeNew7774** [comment]
@zydiaa Hi. Thanks for the suggestions, but can you provide images, drawn on images, so I can see how you would want it to look?

**Comment by zydiaa** [comment]
> @zydiaa Hi. Thanks for the suggestions, but can you provide images, drawn on images, so I can see how you would want it to look?

Something like this (Please ignore my ui skills, i dont know how to copy the colors 😭) 
![image](https://github.com/user-attachments/assets/d687fe27-669a-4ced-976b-846451207003)

**Comment by SpikeNew7774** [comment]
@zydiaa Thanks for the screenshots. I see the problem with the canvases. Let me have a look at that and come back and show you the progress.

**Comment by SpikeNew7774** [comment]
@zydiaa This is the fixed version for canvases:
![image](https://github.com/user-attachments/assets/c4a78e41-7ec0-499e-8cac-efdf5447b06a)

**Comment by SpikeNew7774** [comment]
@zydiaa The problem should now be fixed. Try to close and open Spotify back up, and you should get the fixed version. 😁

**Comment by zydiaa** [comment]
> @zydiaa The problem should now be fixed. Try to close and open Spotify back up, and you should get the fixed version. 😁

yess it looks way better now, could you maybe change the artist text to white, and maybe add lyrics to the now playing screen?

**Comment by SpikeNew7774** [comment]
@zydiaa The artist text is a good idea, and the lyrics on the Now playing screen is also a good idea. I may have a look into that sometime.

**Comment by SpikeNew7774** [comment]
@zydiaa Yes, You need to pause the song first to scroll. I'm thinking of adding a button for it. The scrolling thing other lyrics providers do, was unsuccessful on my side.

**Comment by iam-siphon** [comment]
this **
![image](https://github.com/user-attachments/assets/6ed8e1a0-3c82-4fdf-a397-794c6af7fc6b)
**

**Comment by roranfeed** [comment]
Hi! I really like your extension, so I have a suggestion. I often notice that the lyrics go faster/slower than the song itself, so I suggest adding a delay change to the lyrics output, like in [@CustomApps/lyrics-plus](https://github.com/spicetify/cli/tree/cf47f29268a97377a2a6ef280c34b013fa7d54ba/CustomApps/lyrics-plus), where you can easily adjust this delay with two buttons. Yes, this delay is almost minimal, but it's annoying when the lyrics don't go in sync with the song, especially word-by-word lyrics

**Comment by SpikeNew7774** [comment]
@roranfeed Thats unfortunetaly a Spicetify issue. You can try closing and opening the Spotify app. Just one thing, if you need to submit an issue, you can by creating a new one. I really want to have the issues organized so if you can, please do.
