### ISSUE TITLE
Fullscreen Mode

### ISSUE THREAD

**Issue by Claw256** [SpikeNew7774/spicy-lyrics#44]
Hiya,

First of all, I wanted to say great work in this Spicetify extension! You did some really awesome work.

I'm wondering if you could add fullscreen functionality to the extension, for use with karaoke, etc.

When I press the built-in Spotify fullscreen button, the Spicy Lyrics extension doesn't show up, only the built-in spotify lyrics. See my attached screenshots. Is there a way to fix this, or does the fullscreen mode not exist in this extension yet?

Many thanks 🙏
![Screenshot 2024-12-14 201314](https://github.com/user-attachments/assets/00d56f6a-082f-457c-89c6-f1fa35a9ee5e)
![Screenshot 2024-12-14 201340](https://github.com/user-attachments/assets/030013e0-d249-47c1-ae54-0deb7f4a064e)
![Screenshot 2024-12-14 201349](https://github.com/user-attachments/assets/f958ebe2-0d61-444e-8a3c-e59ca5eb1406)

**Comment by SpikeNew7774** [comment]
@Claw256 Hi. Thanks for the Suggestion! To answer your question, No, Spicy Lyrics currently doesn't have a fullscreen mode. I'll probably add that in the future, but currently, I'm looking into the actual lyrics styling. Thanks!

**Comment by Claw256** [comment]
Perfect. Proper lyrics styling would be a great feature! 

Would you believe it, only a few minutes ago I actually found a workaround to getting your extension into Fullscreen Mode. 

For anyone coming across this in a search in the future, you do the following:

1. Install the surfbryce/beautiful-lyrics extension first from the Spicetify Marketplace
2. Then install @SpikeNew7774 's spicy-lyrics extension.
3. Press the "Spicy Lyrics" button in Spotify
4. Press the "Fullscreen" button in Spotify
5. ???
6. Profit.

I believe the surfbryce/beautiful-lyrics extension has some full-screen typescript dependency that can be used with Spike's extension, as when I press the "Spicy Lyrics" button in Spotify, and then press the "Fullscreen" button, it just works!

See my screenshots for more info.

Thanks again, and keep it the great work!
![Screenshot 2024-12-14 202805](https://github.com/user-attachments/assets/503f9040-8fcc-4914-8392-60f6f3fce876)
![Screenshot 2024-12-14 202815](https://github.com/user-attachments/assets/a5d7f0b8-9628-4799-86d4-a772e0290b47)
![Screenshot 2024-12-14 202825](https://github.com/user-attachments/assets/aeaeb6bd-87bb-46eb-8687-3b69ecc94af4)

**Comment by SpikeNew7774** [comment]
@Claw256 The one in the fullscreen mode is just the surfbryce/beautiful-lyrics and not Spicy Lyrics. But Nice!

**Comment by Claw256** [comment]
> @Claw256 There's Now a fullscreen mode in Spicy Lyrics!

Awesome, thank you. Merry christmas 🙏🙏

**Comment by SpikeNew7774** [comment]
@Claw256 You too! Enjoy!
