### ISSUE TITLE
Now playing view glitch 

### ISSUE THREAD

**Issue by imbadatcoding53** [SpikeNew7774/spicy-lyrics#7]
The album art doesnt work with the Now Playing View 
<img width="434" alt="Screenshot 2024-11-17 at 2 50 00 PM" src="https://github.com/user-attachments/assets/0987d914-db13-4ab2-bd76-dfc4ee77d13d">
Could you make the entire Now Playing View have the gradient.

**Comment by imbadatcoding53** [comment]
Could you also change the size of the icon to match with the other ones because it looks odd 
<img width="332" alt="Screenshot 2024-11-17 at 2 54 05 PM" src="https://github.com/user-attachments/assets/7b4e5c08-67eb-4ee1-9fbd-a645b4a7dcda">

**Comment by imbadatcoding53** [comment]
This might be alot of requests but is it possible to make the lyrics a bit smallers when the player isn't at full size. First image is Beautiful Lyrics
<img width="790" alt="Screenshot 2024-11-17 at 3 01 00 PM" src="https://github.com/user-attachments/assets/1b0f9009-2f17-4a37-a62b-df68d1ff7236">

<img width="785" alt="Screenshot 2024-11-17 at 3 01 15 PM" src="https://github.com/user-attachments/assets/1fcd74f5-eeea-450e-8cc1-805d2ee59269">

**Comment by SpikeNew7774** [comment]
@imbadatcoding53 I will have a look at the font-size. Its probably beacuse its in px and not em. Thanks for the report.

**Comment by imbadatcoding53** [comment]
No rush, I was noticing the Beautiful Lyrics bug and then I stumbled upon your new lyric extension for Spicetify so I decided to give it a try. Continue up the work 👍

**Comment by imbadatcoding53** [comment]
Could you also check the two above suggestions/ bugs

**Comment by SpikeNew7774** [comment]
@imbadatcoding53 Can I see the full Now playing bar. I'm not getting that issue. And also I'll have a look into the icon.

**Comment by SpikeNew7774** [comment]
@imbadatcoding53 That's probably a problem on your side. You probably have enabled the background thingy in the experimental features of Spotify. When you disable that, it should work normally again.

**Comment by SpikeNew7774** [comment]
@imbadatcoding53 The font problem is fixed now.

**Comment by imbadatcoding53** [comment]
Ok thanks!
