### ISSUE TITLE
Prevent DJ from looking for Lyrics

### ISSUE THREAD

**Issue by Alehaaaa** [SpikeNew7774/spicy-lyrics#9]
Hi Spike, thanks for this awesome extension!
With Spotify Premium, there's a "DJ" that plays as a song every now and then. A check to see if the DJ is playing before trying to fetch the Lyrics would prevent too many unnecessary requests.

<img width="967" alt="Screenshot 2024-11-17 at 21 49 43" src="https://github.com/user-attachments/assets/1b5f4cdc-8349-49a8-9ddd-4fae9e5a0277">

**Comment by Alehaaaa** [comment]
If there is anything you need to implement this, let me know :)

**Comment by SpikeNew7774** [comment]
@Alehaaaa That should be fixed. If not, you can notify me by tagging me here!
